import assert from "node:assert/strict";
import { loadProductionRuntime } from "./helpers/load-production-runtime.js";
const tests=[];const test=(name,fn)=>tests.push({name,fn});
const rows=[{id:"doc",internal:"_Document1",object:"Doc",parentId:null},{id:"field",internal:"_Fld1",object:"Value",type:"string",parentId:"doc"}];
function runtime(){const value=loadProductionRuntime();value.api.importRows(rows.map(row=>({...row})));value.api.state.selected={field:true};value.api.state.queryGraphScope="all";value.api.renderSQL();return value;}
test("graph panel exists",()=>assert.match(runtime().html,/id="queryGraphPanel"/));
test("graph mode exists",()=>assert.match(runtime().html,/id="structureViewMode"/));
test("graph filter exists",()=>assert.match(runtime().html,/id="queryGraphFilter"/));
test("graph SVG exists",()=>assert.match(runtime().html,/id="queryGraphSvg"/));
test("model is present",()=>assert.equal(typeof runtime().api.buildQueryGraphModel,"function"));
test("model has nodes",()=>assert.ok(runtime().api.buildQueryGraphModel({rows,selectedIds:["field"],queryPlan:runtime().api.state.queryPlan}).nodes.length));
test("model has tree edge",()=>assert.equal(runtime().api.buildQueryGraphModel({rows,selectedIds:[],queryPlan:null}).edges[0].kind,"tree"));
test("selected field is active",()=>assert.ok(runtime().api.buildQueryGraphModel({rows,selectedIds:["field"],queryPlan:null}).activeNodeIds.includes("row:field")));
test("model is deterministic",()=>{const value=runtime(),input={rows:value.api.state.rows,selectedIds:["field"],metaById:{},queryPlan:value.api.state.queryPlan};assert.deepEqual(value.api.buildQueryGraphModel(input),value.api.buildQueryGraphModel(input))});
test("renderer writes graph counts",()=>{const value=runtime();value.api.renderQueryGraph();assert.match(value.elements.get("queryGraphNodeCount").textContent,/Узлов/) });
test("tree edge is classified as available",()=>{const value=runtime();const model=value.api.buildQueryGraphModel({rows,selectedIds:[],queryPlan:null});const edge=model.edges.find(e=>e.kind==="tree");assert.ok(edge);assert.equal(value.api.normalizeRelationshipStatus(edge,model),"available");});
test("active selected field node is active-sql",()=>{const value=runtime();const model=value.api.buildQueryGraphModel({rows,selectedIds:["field"],queryPlan:null});const node=model.nodes.find(n=>n.id==="row:field");assert.ok(node);assert.equal(value.api.normalizeRelationshipStatus(node,model),"active-sql");});
test("active filter shows only active edges/nodes",()=>{const value=runtime();value.api.state.queryGraph.graphFilter="active";value.api.renderQueryGraph();assert.match(value.elements.get("queryGraphNodes").innerHTML,/row:field/);});
test("focus reset clears presentation focus",()=>{const value=runtime();value.api.setQueryGraphFocus("node","row:field");assert.equal(value.api.state.queryGraphFocus.id,"row:field");value.api.clearQueryGraphFocus();assert.equal(value.api.state.queryGraphFocus.id,null);});
test("details card includes relationship kind",()=>{const value=runtime();const model=value.api.buildQueryGraphModel({rows,selectedIds:[],queryPlan:null});const edge=model.edges[0];const details=value.api.buildRelationshipDetails(edge,model);assert.ok(details.some(row=>row.label==="Тип"));});

test("final rendered node keeps a working click handler",()=>{const value=runtime();const host=value.elements.get("queryGraphNodes");const node=host.querySelectorAll("[data-node-id]").find(item=>item.getAttribute("data-node-id")==="row:field");assert.ok(node,"final row:field DOM node is missing");const beforeSelection=JSON.stringify(value.api.state.selected),beforePlan=value.api.state.queryPlan,beforeSql=value.elements.get("sql").value;node.dispatchEvent({type:"click"});assert.equal(value.api.state.queryGraphFocus.kind,"node");assert.equal(value.api.state.queryGraphFocus.id,"row:field");assert.equal(JSON.stringify(value.api.state.selected),beforeSelection);assert.equal(value.api.state.queryPlan,beforePlan);assert.equal(value.elements.get("sql").value,beforeSql);});
test("final rendered edge keeps a working click handler",()=>{const value=runtime();const host=value.elements.get("queryGraphNodes");const edge=host.querySelectorAll("[data-edge-id]").find(item=>item.getAttribute("data-edge-id")==="tree:doc:field");assert.ok(edge,"final tree:doc:field DOM edge is missing");edge.dispatchEvent({type:"click"});assert.equal(value.api.state.queryGraphFocus.kind,"edge");assert.equal(value.api.state.queryGraphFocus.id,"tree:doc:field");});
test("repeated render does not double-run node or edge handlers",()=>{const value=runtime();value.api.renderQueryGraph();value.api.renderQueryGraph();let host=value.elements.get("queryGraphNodes");const node=host.querySelectorAll("[data-node-id]").find(item=>item.getAttribute("data-node-id")==="row:field");node.dispatchEvent({type:"click"});assert.equal(value.api.state.queryGraphFocus.kind,"node");assert.equal(value.api.state.queryGraphFocus.id,"row:field");value.api.clearQueryGraphFocus();host=value.elements.get("queryGraphNodes");const edge=host.querySelectorAll("[data-edge-id]").find(item=>item.getAttribute("data-edge-id")==="tree:doc:field");edge.dispatchEvent({type:"click"});assert.equal(value.api.state.queryGraphFocus.kind,"edge");assert.equal(value.api.state.queryGraphFocus.id,"tree:doc:field");});
test("Escape clears node focus without changing semantic state",()=>{const value=runtime();value.api.setQueryGraphFocus("node","row:field");const beforeSelection=JSON.stringify(value.api.state.selected),beforePlan=value.api.state.queryPlan,beforeSql=value.elements.get("sql").value;value.runtime.dispatchEvent({type:"keydown",key:"Escape"});assert.equal(value.api.state.queryGraphFocus.kind,null);assert.equal(value.api.state.queryGraphFocus.id,null);assert.doesNotMatch(value.elements.get("queryGraphNodes").innerHTML,/\b(?:focus|dim)\b/);assert.equal(value.elements.get("queryGraphDetails").innerHTML,"");assert.equal(JSON.stringify(value.api.state.selected),beforeSelection);assert.equal(value.api.state.queryPlan,beforePlan);assert.equal(value.elements.get("sql").value,beforeSql);});
test("Escape clears edge focus without changing semantic state",()=>{const value=runtime();value.api.setQueryGraphFocus("edge","tree:doc:field");const beforeSelection=JSON.stringify(value.api.state.selected),beforePlan=value.api.state.queryPlan,beforeSql=value.elements.get("sql").value;value.runtime.dispatchEvent({type:"keydown",key:"Escape"});assert.equal(value.api.state.queryGraphFocus.kind,null);assert.equal(value.api.state.queryGraphFocus.id,null);assert.doesNotMatch(value.elements.get("queryGraphNodes").innerHTML,/\b(?:focus|dim)\b/);assert.equal(value.elements.get("queryGraphDetails").innerHTML,"");assert.equal(JSON.stringify(value.api.state.selected),beforeSelection);assert.equal(value.api.state.queryPlan,beforePlan);assert.equal(value.elements.get("sql").value,beforeSql);});
test("repeated Escape with empty focus is safe",()=>{const value=runtime();value.api.clearQueryGraphFocus();const beforeSelection=JSON.stringify(value.api.state.selected),beforePlan=value.api.state.queryPlan,beforeSql=value.elements.get("sql").value;assert.doesNotThrow(()=>value.runtime.dispatchEvent({type:"keydown",key:"Escape"}));assert.equal(value.api.state.queryGraphFocus.kind,null);assert.equal(value.api.state.queryGraphFocus.id,null);assert.equal(JSON.stringify(value.api.state.selected),beforeSelection);assert.equal(value.api.state.queryPlan,beforePlan);assert.equal(value.elements.get("sql").value,beforeSql);});

test("query scope empty state is specific",()=>{const value=runtime();value.api.state.queryGraphScope="query";value.api.state.queryPlan={status:"ready",sqlParts:{empty:true},selections:[],joins:[],filters:[],diagnostics:[]};value.api.renderQueryGraph();assert.match(value.elements.get("queryGraphEmpty").textContent,/Выберите поля/);});
test("query scope blocked state preserves canonical reason",()=>{const value=runtime();value.api.state.queryGraphScope="query";value.api.state.queryPlan={status:"blocked",reason:"missing_metadata",diagnostics:["missing_metadata"],selections:[],joins:[],filters:[]};value.api.renderQueryGraph();assert.match(value.elements.get("queryGraphEmpty").textContent,/missing_metadata/);assert.equal(value.elements.get("queryGraphNodes").innerHTML,"");});
test("query graph presentation reserves alias-first node and compact edge classes",()=>{const html=runtime().html;assert.match(html,/query-graph-node-alias/);assert.match(html,/query-graph-node-table/);assert.match(html,/query-graph-node-role/);assert.match(html,/compactQueryEdgeLabel/);assert.match(html,/Таблиц:/);});
test("focused query node adds confirmed related field through canonical selection",()=>{const value=loadProductionRuntime();value.api.importRows([{id:"doc",internal:"_Document1",object:"Document",parentId:null},{id:"partner",internal:"_Fld1RRef",object:"Partner",title:"Partner",type:"Справочник.Partners",parentId:"doc"},{id:"partners",internal:"_Reference1",object:"Partners",type:"Справочник.Partners",parentId:null},{id:"name",internal:"_Fld2",object:"Name",title:"Name",type:"Строка",parentId:"partners"}]);value.api.state.selected={partner:true};value.api.renderSQL();value.api.state.queryGraphScope="query";const node=value.api.renderQueryGraph().nodes[0];value.api.setQueryGraphFocus("node",node.id);assert.match(value.elements.get("queryGraphDetails").innerHTML,/Доступные связанные данные/);assert.equal(value.api.addGraphRelatedField("reference:partner:_Reference1","_Fld2"),true);assert.ok(value.api.state.selected["s:partner:1:_Reference1:_Fld2"]);assert.match(value.elements.get("sql").value,/R1\.\[_Fld2\]/);assert.match(value.elements.get("sql").value,/LEFT JOIN/);});
test("graph add preserves canonical filters and project round trip",()=>{const value=loadProductionRuntime(),rows=[{id:"doc",internal:"_Document1",object:"Document",parentId:null},{id:"amount",internal:"_FldAmount",object:"Amount",type:"decimal(10,2)",parentId:"doc"},{id:"partner",internal:"_FldPartnerRRef",object:"Partner",type:"Справочник.Partners",parentId:"doc"},{id:"partners",internal:"_Reference1",object:"Partners",type:"Справочник.Partners",parentId:null},{id:"name",internal:"_FldName",object:"Name",type:"string",parentId:"partners"}];value.api.importRows(rows);value.api.state.selected={amount:true,partner:true};value.api.state.filters=[{id:"amount-filter",fieldId:"amount",operator:"gte",value:"10"}];value.api.renderSQL();assert.equal(value.api.addGraphRelatedField("reference:partner:_Reference1","_FldName"),true);const id="s:partner:1:_Reference1:_FldName",before=value.elements.get("sql").value,snapshot=value.api.createProjectSnapshot();assert.match(before,/CAST\(T\.\[_FldAmount\] AS decimal\(10,2\)\) >= 10/);assert.match(before,/R1\.\[_FldName\]/);assert.equal((before.match(/LEFT JOIN/g)||[]).length,1);value.api.applyProjectSnapshot(snapshot);assert.ok(value.api.state.selected[id]);assert.equal(JSON.stringify(value.api.state.filters),JSON.stringify([{id:"amount-filter",fieldId:"amount",operator:"gte",value:"10"}]));assert.equal(value.elements.get("sql").value,before);assert.equal(snapshot.appVersion,"0.2.3");});
let passed=0,failed=0;for(const item of tests){try{item.fn();console.log(`ok ${++passed} - ${item.name}`)}catch(error){failed+=1;console.error(`not ok - ${item.name}`);console.error(error);}}if(failed)throw new Error(`${failed} production query graph tests failed`);console.log(`\n${passed} production query graph tests passed`);
