import assert from "node:assert/strict";
import { loadProductionRuntime } from "./helpers/load-production-runtime.js";
const tests=[];const test=(name,fn)=>tests.push({name,fn});
const rows=[{id:"doc",internal:"_Document1",object:"Doc",parentId:null},{id:"field",internal:"_Fld1",object:"Value",type:"string",parentId:"doc"}];
function runtime(){const value=loadProductionRuntime();value.api.importRows(rows.map(row=>({...row})));value.api.state.selected={field:true};value.api.state.queryGraphScope="all";value.api.renderSQL();return value;}
test("graph panel exists",()=>assert.match(runtime().html,/id="queryGraphPanel"/));
test("graph mode exists",()=>assert.match(runtime().html,/id="structureViewMode"/));
test("graph filter exists",()=>assert.match(runtime().html,/id="queryGraphFilter"/));
test("graph SVG exists",()=>assert.match(runtime().html,/id="queryGraphSvg"/));
test("model is present",()=>assert.equal(typeof runtime().api.buildQueryGraphModel,"function"));
test("model has nodes",()=>assert.ok(runtime().api.buildQueryGraphModel({rows,selectedIds:["field"],queryPlan:runtime().api.state.queryPlan}).nodes.length));
test("model has tree edge",()=>assert.equal(runtime().api.buildQueryGraphModel({rows,selectedIds:[],queryPlan:null}).edges[0].kind,"tree"));
test("selected field is active",()=>assert.ok(runtime().api.buildQueryGraphModel({rows,selectedIds:["field"],queryPlan:null}).activeNodeIds.includes("row:field")));
test("model is deterministic",()=>{const value=runtime(),input={rows:value.api.state.rows,selectedIds:["field"],metaById:{},queryPlan:value.api.state.queryPlan};assert.deepEqual(value.api.buildQueryGraphModel(input),value.api.buildQueryGraphModel(input))});
test("renderer writes graph counts",()=>{const value=runtime();value.api.renderQueryGraph();assert.match(value.elements.get("queryGraphNodeCount").textContent,/Узлов/) });
test("tree edge is classified as available",()=>{const value=runtime();const model=value.api.buildQueryGraphModel({rows,selectedIds:[],queryPlan:null});const edge=model.edges.find(e=>e.kind==="tree");assert.ok(edge);assert.equal(value.api.normalizeRelationshipStatus(edge,model),"available");});
test("active selected field node is active-sql",()=>{const value=runtime();const model=value.api.buildQueryGraphModel({rows,selectedIds:["field"],queryPlan:null});const node=model.nodes.find(n=>n.id==="row:field");assert.ok(node);assert.equal(value.api.normalizeRelationshipStatus(node,model),"active-sql");});
test("active filter shows only active edges/nodes",()=>{const value=runtime();value.api.state.queryGraph.graphFilter="active";value.api.renderQueryGraph();assert.match(value.elements.get("queryGraphNodes").innerHTML,/row:field/);});
test("focus reset clears presentation focus",()=>{const value=runtime();value.api.setQueryGraphFocus("node","row:field");assert.equal(value.api.state.queryGraphFocus.id,"row:field");value.api.clearQueryGraphFocus();assert.equal(value.api.state.queryGraphFocus.id,null);});
test("details card includes relationship kind",()=>{const value=runtime();const model=value.api.buildQueryGraphModel({rows,selectedIds:[],queryPlan:null});const edge=model.edges[0];const details=value.api.buildRelationshipDetails(edge,model);assert.ok(details.some(row=>row.label==="Тип"));});

test("final rendered node keeps a working click handler",()=>{const value=runtime();const host=value.elements.get("queryGraphNodes");const node=host.querySelectorAll("[data-node-id]").find(item=>item.getAttribute("data-node-id")==="row:field");assert.ok(node,"final row:field DOM node is missing");const beforeSelection=JSON.stringify(value.api.state.selected),beforePlan=value.api.state.queryPlan,beforeSql=value.elements.get("sql").value;node.dispatchEvent({type:"click"});assert.equal(value.api.state.queryGraphFocus.kind,"node");assert.equal(value.api.state.queryGraphFocus.id,"row:field");assert.equal(JSON.stringify(value.api.state.selected),beforeSelection);assert.equal(value.api.state.queryPlan,beforePlan);assert.equal(value.elements.get("sql").value,beforeSql);});
test("final rendered edge keeps a working click handler",()=>{const value=runtime();const host=value.elements.get("queryGraphNodes");const edge=host.querySelectorAll("[data-edge-id]").find(item=>item.getAttribute("data-edge-id")==="tree:doc:field");assert.ok(edge,"final tree:doc:field DOM edge is missing");edge.dispatchEvent({type:"click"});assert.equal(value.api.state.queryGraphFocus.kind,"edge");assert.equal(value.api.state.queryGraphFocus.id,"tree:doc:field");});
test("repeated render does not double-run node or edge handlers",()=>{const value=runtime();value.api.renderQueryGraph();value.api.renderQueryGraph();let host=value.elements.get("queryGraphNodes");const node=host.querySelectorAll("[data-node-id]").find(item=>item.getAttribute("data-node-id")==="row:field");node.dispatchEvent({type:"click"});assert.equal(value.api.state.queryGraphFocus.kind,"node");assert.equal(value.api.state.queryGraphFocus.id,"row:field");value.api.clearQueryGraphFocus();host=value.elements.get("queryGraphNodes");const edge=host.querySelectorAll("[data-edge-id]").find(item=>item.getAttribute("data-edge-id")==="tree:doc:field");edge.dispatchEvent({type:"click"});assert.equal(value.api.state.queryGraphFocus.kind,"edge");assert.equal(value.api.state.queryGraphFocus.id,"tree:doc:field");});
test("Escape clears node focus without changing semantic state",()=>{const value=runtime();value.api.setQueryGraphFocus("node","row:field");const beforeSelection=JSON.stringify(value.api.state.selected),beforePlan=value.api.state.queryPlan,beforeSql=value.elements.get("sql").value;value.runtime.dispatchEvent({type:"keydown",key:"Escape"});assert.equal(value.api.state.queryGraphFocus.kind,null);assert.equal(value.api.state.queryGraphFocus.id,null);assert.doesNotMatch(value.elements.get("queryGraphNodes").innerHTML,/\b(?:focus|dim)\b/);assert.equal(value.elements.get("queryGraphDetails").innerHTML,"");assert.equal(JSON.stringify(value.api.state.selected),beforeSelection);assert.equal(value.api.state.queryPlan,beforePlan);assert.equal(value.elements.get("sql").value,beforeSql);});
test("Escape clears edge focus without changing semantic state",()=>{const value=runtime();value.api.setQueryGraphFocus("edge","tree:doc:field");const beforeSelection=JSON.stringify(value.api.state.selected),beforePlan=value.api.state.queryPlan,beforeSql=value.elements.get("sql").value;value.runtime.dispatchEvent({type:"keydown",key:"Escape"});assert.equal(value.api.state.queryGraphFocus.kind,null);assert.equal(value.api.state.queryGraphFocus.id,null);assert.doesNotMatch(value.elements.get("queryGraphNodes").innerHTML,/\b(?:focus|dim)\b/);assert.equal(value.elements.get("queryGraphDetails").innerHTML,"");assert.equal(JSON.stringify(value.api.state.selected),beforeSelection);assert.equal(value.api.state.queryPlan,beforePlan);assert.equal(value.elements.get("sql").value,beforeSql);});
test("repeated Escape with empty focus is safe",()=>{const value=runtime();value.api.clearQueryGraphFocus();const beforeSelection=JSON.stringify(value.api.state.selected),beforePlan=value.api.state.queryPlan,beforeSql=value.elements.get("sql").value;assert.doesNotThrow(()=>value.runtime.dispatchEvent({type:"keydown",key:"Escape"}));assert.equal(value.api.state.queryGraphFocus.kind,null);assert.equal(value.api.state.queryGraphFocus.id,null);assert.equal(JSON.stringify(value.api.state.selected),beforeSelection);assert.equal(value.api.state.queryPlan,beforePlan);assert.equal(value.elements.get("sql").value,beforeSql);});

let passed=0,failed=0;for(const item of tests){try{item.fn();console.log(`ok ${++passed} - ${item.name}`)}catch(error){failed+=1;console.error(`not ok - ${item.name}`);console.error(error);}}if(failed)throw new Error(`${failed} production query graph tests failed`);console.log(`\n${passed} production query graph tests passed`);
