import assert from "node:assert/strict";
import fs from "node:fs";
import crypto from "node:crypto";
import { buildQueryPlan } from "../src/core/queryPlan.js";
import { loadProductionRuntime } from "./helpers/load-production-runtime.js";
import { buildEmbeddedBlock, verify } from "../scripts/sync-production-core.mjs";
const tests=[]; const test=(name,fn)=>tests.push({name,fn}); const html=fs.readFileSync("index.html","utf8"); const normalized=value=>JSON.parse(JSON.stringify(value));
const fixture=()=>{const rows=[{id:"doc",internal:"_Document1",object:"D",parentId:null},{id:"value",internal:"_Fld1",object:"V",type:"string",parentId:"doc"}];return {rows,byId:Object.fromEntries(rows.map(x=>[x.id,x])),selected:{value:true},metaById:{},schema:"dbo"};};
test("entry bundle is generated",()=>assert.match(buildEmbeddedBlock(),/buildQueryPlan/));
test("generated block begins",()=>assert.match(html,/BEGIN GENERATED CANONICAL CORE/));
test("generated block ends",()=>assert.match(html,/END GENERATED CANONICAL CORE/));
test("markers are unique",()=>assert.equal((html.match(/BEGIN GENERATED CANONICAL CORE/g)||[]).length,1));
test("generated block is unique",()=>assert.equal((html.match(/END GENERATED CANONICAL CORE/g)||[]).length,1));
test("block is nonempty",()=>assert.ok(buildEmbeddedBlock().length>1000));
test("manifest exists",()=>assert.match(html,/SQLBI_CANONICAL_MANIFEST/));
test("source hash exists",()=>assert.match(html,/sha256/));
test("payload is deterministic",()=>assert.equal(buildEmbeddedBlock(),buildEmbeddedBlock()));
test("sync check passes",()=>assert.equal(verify(html),true));
test("stale payload fails",()=>assert.throws(()=>verify(html.replace("Generated from canonical","Changed"))));
test("missing marker fails",()=>assert.throws(()=>verify(html.replace("<!-- BEGIN GENERATED CANONICAL CORE -->",""))));
test("duplicate marker fails",()=>assert.throws(()=>verify(html.replace("<!-- END GENERATED CANONICAL CORE -->","<!-- BEGIN GENERATED CANONICAL CORE --><!-- END GENERATED CANONICAL CORE -->"))));
test("embedded runtime loads",()=>assert.ok(loadProductionRuntime().canonicalCore));
test("namespace is singular",()=>assert.equal(typeof loadProductionRuntime().canonicalCore,"object"));
test("buildQueryPlan exported",()=>assert.equal(typeof loadProductionRuntime().canonicalCore.buildQueryPlan,"function"));
test("generateSql exported",()=>assert.equal(typeof loadProductionRuntime().canonicalCore.generateSql,"function"));
test("no dynamic import",()=>assert.equal(/import\s*\(/.test(buildEmbeddedBlock()),false));
test("no module syntax",()=>assert.equal(/\bimport\s+/.test(buildEmbeddedBlock()),false));
test("no Node require",()=>assert.equal(/require\(/.test(buildEmbeddedBlock()),false));
test("no filesystem",()=>assert.equal(/node:fs|readFileSync/.test(buildEmbeddedBlock()),false));
test("physical plan parity",()=>assert.deepEqual(normalized(loadProductionRuntime().canonicalCore.buildQueryPlan(fixture())),normalized(buildQueryPlan(fixture()))));
test("physical status parity",()=>assert.equal(loadProductionRuntime().canonicalCore.buildQueryPlan(fixture()).status,"ready"));
test("physical SQL parts parity",()=>assert.deepEqual(normalized(loadProductionRuntime().canonicalCore.buildQueryPlan(fixture()).sqlParts),normalized(buildQueryPlan(fixture()).sqlParts)));
test("repeated embedded plan deterministic",()=>assert.deepEqual(normalized(loadProductionRuntime().canonicalCore.buildQueryPlan(fixture())),normalized(loadProductionRuntime().canonicalCore.buildQueryPlan(fixture()))));
test("embedded plan does not mutate input",()=>{const x=fixture(),before=JSON.stringify(x);loadProductionRuntime().canonicalCore.buildQueryPlan(x);assert.equal(JSON.stringify(x),before)});
test("payload hash is valid",()=>{const block=buildEmbeddedBlock(),m=block.match(/payloadSha256":"([a-f0-9]+)"/)[1];const payload=block.match(/SQLBI_CANONICAL_MANIFEST [^\n]*\n([\s\S]*)<!-- END GENERATED CANONICAL CORE -->/)[1];assert.equal(crypto.createHash("sha256").update(payload).digest("hex"),m)});
test("block has no timestamps",()=>assert.equal(/202\d-\d\d-\d\dT/.test(buildEmbeddedBlock()),false));
test("core bootstrap is isolated",()=>assert.notEqual(loadProductionRuntime().canonicalCore,loadProductionRuntime().canonicalCore));
test("HTML before block is preserved by generated contract",()=>assert.ok(html.indexOf("<!DOCTYPE html>")<html.indexOf("BEGIN GENERATED")));
let passed=0;for(const item of tests){item.fn();console.log(`ok ${++passed} - ${item.name}`)}console.log(`\n${passed} production core embed tests passed`);
