import { parseNumericType } from "./casts.js";
import { isBoolType, isDateField, isReferenceField } from "./types.js";
const OPS={boolean:new Set(["is_true","is_false"]),text:new Set(["eq","ne","contains","starts_with","ends_with","is_null","is_not_null"]),number:new Set(["eq","ne","gt","gte","lt","lte","between","is_null","is_not_null"]),date:new Set(["eq","before","after","between","is_null","is_not_null"]),reference:new Set(["eq","ne","is_null","is_not_null"])};
const nullOps=new Set(["is_null","is_not_null"]);
export function filterFieldType(field={}){if(isBoolType(field.type))return "boolean";if(isDateField(field))return "date";if(isReferenceField(field))return "reference";if(parseNumericType(field.type).matched||/^(?:int|integer|bigint)$/iu.test(String(field.type||"").trim()))return "number";return "text";}
const text=v=>typeof v==="string"?`N'${v.replace(/'/g,"''")}'`:null;
const number=v=>{const s=String(v??"").trim();return /^-?(?:\d+|\d+\.\d+|\.\d+)$/u.test(s)&&Number.isFinite(Number(s))?s:null;};
const date=v=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/u.test(v)&&!Number.isNaN(Date.parse(`${v}T00:00:00Z`))?text(v):null;
const guid=v=>typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(v.trim())?text(v.trim().toLowerCase()):null;
const invalid=(i,f,o,reason)=>({ok:false,diagnostic:`Filter ${i+1} (${f||"<missing>"}, ${o||"<missing>"}): ${reason}.`});
export function normalizeFilters(filters,selections){if(filters==null)return{ok:true,filters:[]};if(!Array.isArray(filters))return invalid(0,"","","filter list is malformed");const selected=new Map(selections.map(s=>[String(s.id),s]));const out=[];for(let i=0;i<filters.length;i++){const x=filters[i];if(!x||typeof x!=="object"||Array.isArray(x))return invalid(i,"","","filter is malformed");const fieldId=typeof x.fieldId==="string"?x.fieldId:"",operator=typeof x.operator==="string"?x.operator:"",selection=selected.get(fieldId);if(!selection)return invalid(i,fieldId,operator,"field is not selected or has no resolved physical origin");const kind=filterFieldType(selection.field);if(!OPS[kind].has(operator))return invalid(i,fieldId,operator,`operator is not valid for ${kind}`);const base={id:typeof x.id==="string"&&x.id?x.id:`filter-${i+1}`,fieldId,operator,kind,expression:selection.expression};if(nullOps.has(operator)||kind==="boolean"){out.push(base);continue;}const convert=kind==="number"?number:kind==="date"?date:kind==="reference"?guid:text;if(operator==="between"){const vals=Array.isArray(x.values)?x.values:[],a=convert(vals[0]),b=convert(vals[1]);if(!a||!b)return invalid(i,fieldId,operator,"between requires two valid values");out.push({...base,values:[a,b]});}else{const value=convert(x.value);if(!value)return invalid(i,fieldId,operator,"missing or invalid value");out.push({...base,value});}}return{ok:true,filters:out};}
export function renderFilterCondition(f){const e=f.expression;if(f.operator==="is_null")return `${e} IS NULL`;if(f.operator==="is_not_null")return `${e} IS NOT NULL`;if(f.operator==="is_true")return `${e} = 1`;if(f.operator==="is_false")return `${e} = 0`;if(f.operator==="between")return `${e} BETWEEN ${f.values[0]} AND ${f.values[1]}`;if(f.operator==="contains")return `${e} LIKE N'%' + ${f.value} + N'%'`;if(f.operator==="starts_with")return `${e} LIKE ${f.value} + N'%'`;if(f.operator==="ends_with")return `${e} LIKE N'%' + ${f.value}`;return `${e} ${({eq:"=",ne:"<>",gt:">",gte:">=",lt:"<",lte:"<=",before:"<",after:">"})[f.operator]} ${f.value}`;}
export function legacyBooleanFilters(values={}){return Object.entries(values).flatMap(([fieldId,v])=>v&&v.yes&&!v.no?[{id:`legacy-bool-${fieldId}`,fieldId,operator:"is_true"}]:v&&v.no&&!v.yes?[{id:`legacy-bool-${fieldId}`,fieldId,operator:"is_false"}]:[]);}
